// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Execute } from "./Execute";

export type Action = { Exec: Execute } | "None";