// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimeZone } from "./TimeZone";

export interface DateTime { year: number, month: number, day: number, hour: number, min: number, sec: number, timestamp: bigint, time_zone: TimeZone, }