// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Duration { year: number, month: number, day: number, hour: number, min: number, sec: number, total_sec: bigint, }