// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Action } from "./Action";
import type { DoIfRunning } from "./DoIfRunning";
import type { Logger } from "./Logger";
import type { Status } from "./Status";
import type { Trigger } from "./Trigger";

export interface Entry { id: number, name: string, action: Action, logger: Logger, trigger: Trigger, status: Status, do_if_running: DoIfRunning, enabled: boolean, }