// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SystemUser } from "./SystemUser";

export interface Execute { env: Record<string, string> | null, working_dir: string | null, executable: string, user: SystemUser | null, args: Array<string> | null, }