// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateTime } from "./DateTime";
import type { Duration } from "./Duration";

export type Timer = { Repeat: Duration } | { Once: DateTime } | { ManyTimes: [Duration, number] } | "Never";