// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateTime } from "./DateTime";

export interface TriggerState { exec_time: DateTime | null, exec_times: number, }