// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Entry } from "./Entry";
import type { Process } from "./Process";
import type { Status } from "./Status";
import type { TriggerState } from "./TriggerState";

export interface Work { status: Status, entry: Entry, trigger_state: TriggerState, running_processes: Array<Process>, }